# Generated by Django 5.2.17 on 2026-09-25 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_system",
                    models.CharField(max_length=30, verbose_name="sistema de origem"),
                ),
                (
                    "source_document_id",
                    models.CharField(max_length=100, verbose_name="ID original"),
                ),
                (
                    "source_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="dados recebidos"
                    ),
                ),
                (
                    "document_type",
                    models.CharField(max_length=10, verbose_name="tipo de documento"),
                ),
                (
                    "document_number",
                    models.CharField(max_length=60, verbose_name="número"),
                ),
                ("series", models.CharField(max_length=60, verbose_name="série")),
                ("document_date", models.DateField(verbose_name="data")),
                (
                    "customer_name",
                    models.CharField(max_length=200, verbose_name="cliente"),
                ),
                (
                    "customer_nif",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="NIF do cliente"
                    ),
                ),
                (
                    "currency",
                    models.CharField(default="AOA", max_length=3, verbose_name="moeda"),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, max_digits=18, verbose_name="subtotal"
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=18, verbose_name="imposto"
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, max_digits=18, verbose_name="total"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendente"),
                            ("IMPORTED", "Importada"),
                            ("VALIDATED", "Validada"),
                            ("QUEUED", "Em fila"),
                            ("SENT", "Enviada"),
                            ("CONFIRMED", "Validada pela AGT"),
                            ("REJECTED", "Rejeitada"),
                            ("ERROR", "Erro"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=10,
                        verbose_name="estado",
                    ),
                ),
                (
                    "validation_errors",
                    models.JSONField(
                        blank=True, default=list, verbose_name="erros de validação"
                    ),
                ),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "agt_request_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="request ID AGT"
                    ),
                ),
                (
                    "agt_response",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="resposta AGT"
                    ),
                ),
                (
                    "agt_message",
                    models.TextField(blank=True, verbose_name="mensagem AGT"),
                ),
                (
                    "simulated",
                    models.BooleanField(default=False, verbose_name="simulação"),
                ),
                (
                    "send_attempts",
                    models.PositiveIntegerField(
                        default=0, verbose_name="tentativas de envio"
                    ),
                ),
                ("queued_at", models.DateTimeField(blank=True, null=True)),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="data de envio"
                    ),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "fatura",
                "verbose_name_plural": "faturas",
                "ordering": ["-document_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_number", models.PositiveIntegerField(verbose_name="linha")),
                (
                    "product_code",
                    models.CharField(blank=True, max_length=60, verbose_name="código"),
                ),
                (
                    "description",
                    models.CharField(max_length=500, verbose_name="descrição"),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4, max_digits=18, verbose_name="quantidade"
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=4, max_digits=18, verbose_name="preço unitário"
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        verbose_name="desconto",
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=7,
                        verbose_name="taxa de imposto (%)",
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=18, verbose_name="imposto"
                    ),
                ),
                (
                    "tax_exemption_code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="código de isenção"
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=18,
                        verbose_name="total (sem imposto)",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="invoices.invoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "linha de fatura",
                "verbose_name_plural": "linhas de fatura",
                "ordering": ["line_number"],
            },
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["company", "status"], name="invoices_in_company_918a9b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                fields=("company", "source_system", "source_document_id"),
                name="uniq_invoice_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                fields=("company", "document_type", "series", "document_number"),
                name="uniq_invoice_fiscal_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoiceitem",
            constraint=models.UniqueConstraint(
                fields=("invoice", "line_number"), name="uniq_invoice_line"
            ),
        ),
    ]
