# Generated by Django 5.2.17 on 2026-09-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=2, max_digits=15, verbose_name="subtotal"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="tax_amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=15, verbose_name="imposto"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="total",
            field=models.DecimalField(
                decimal_places=2, max_digits=15, verbose_name="total"
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="discount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=15, verbose_name="desconto"
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="quantity",
            field=models.DecimalField(
                decimal_places=4, max_digits=15, verbose_name="quantidade"
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="tax_amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=15, verbose_name="imposto"
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="total",
            field=models.DecimalField(
                decimal_places=2, max_digits=15, verbose_name="total (sem imposto)"
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=4, max_digits=15, verbose_name="preço unitário"
            ),
        ),
    ]
