# Generated by Django 5.2.17 on 2026-09-25 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0002_amount_precision_portable"),
        ("sources", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="content_hash",
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name="invoice",
            name="last_error",
            field=models.TextField(blank=True, verbose_name="último erro"),
        ),
        migrations.AddField(
            model_name="invoice",
            name="next_attempt_at",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="próxima tentativa"
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="sources.datasource",
                verbose_name="origem",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pendente"),
                    ("IMPORTED", "Importada"),
                    ("VALIDATED", "Validada"),
                    ("QUEUED", "Em fila"),
                    ("SENDING", "A enviar"),
                    ("SENT", "Enviada"),
                    ("CONFIRMED", "Validada pela AGT"),
                    ("REJECTED", "Rejeitada"),
                    ("ERROR", "Erro"),
                ],
                db_index=True,
                default="PENDING",
                max_length=10,
                verbose_name="estado",
            ),
        ),
    ]
