# Generated by Django 5.2.17 on 2026-09-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0003_invoice_content_hash_invoice_last_error_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="network_wait_since",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="à espera de ligação à AGT desde"
            ),
        ),
    ]
