# Generated by Django 5.2.17 on 2026-09-25 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0004_network_wait"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="document_hash",
            field=models.TextField(
                blank=True,
                help_text="Valor original do sistema de faturação (o Gateway não assina).",
                verbose_name="hash / assinatura da fatura",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="hash_control",
            field=models.CharField(
                blank=True,
                max_length=70,
                verbose_name="controlo do hash (versão da chave)",
            ),
        ),
    ]
