# Generated by Django 5.2.17 on 2026-09-25 14:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0002_host_connection_validator"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgtConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "environment",
                    models.CharField(
                        choices=[
                            ("SIMULATION", "Simulação (nada é enviado à AGT)"),
                            ("TEST", "Testes da AGT"),
                            ("PRODUCTION", "Produção"),
                        ],
                        default="SIMULATION",
                        max_length=12,
                        verbose_name="ambiente",
                    ),
                ),
                (
                    "base_url",
                    models.URLField(
                        blank=True,
                        help_text="Endereço oficial indicado pela AGT para o ambiente escolhido (https).",
                        verbose_name="endereço do serviço AGT",
                    ),
                ),
                (
                    "software_certificate_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="n.º de certificado do software",
                    ),
                ),
                (
                    "software_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="nome do software"
                    ),
                ),
                (
                    "software_version",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="versão do software"
                    ),
                ),
                (
                    "client_id",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="client ID"
                    ),
                ),
                (
                    "credentials_prefix",
                    models.CharField(
                        blank=True,
                        help_text="Vazio: usa AGT_CLIENT_SECRET, AGT_PRIVATE_KEY... do .env. X: usa AGT_X_CLIENT_SECRET, ...",
                        max_length=30,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Za-z][A-Za-z0-9_]{0,29}$",
                                "Letras, números e _, a começar por letra (ex.: HOTEL2).",
                            )
                        ],
                        verbose_name="prefixo das credenciais",
                    ),
                ),
                (
                    "auto_send",
                    models.BooleanField(
                        default=False,
                        help_text="Coloca na fila de envio os documentos validados.",
                        verbose_name="enviar automaticamente",
                    ),
                ),
                (
                    "timeout_seconds",
                    models.PositiveIntegerField(
                        default=30,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(300),
                        ],
                        verbose_name="tempo limite (s)",
                    ),
                ),
                (
                    "max_attempts",
                    models.PositiveIntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                        verbose_name="máximo de tentativas",
                    ),
                ),
                (
                    "retry_delay_seconds",
                    models.PositiveIntegerField(
                        default=300,
                        help_text="Duplica a cada tentativa falhada (máximo 24 h).",
                        validators=[
                            django.core.validators.MinValueValidator(10),
                            django.core.validators.MaxValueValidator(86400),
                        ],
                        verbose_name="espera entre tentativas (s)",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agt_config",
                        to="companies.company",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "configuração AGT",
                "verbose_name_plural": "configurações AGT",
            },
        ),
    ]
