# Generated by Django 5.2.17 on 2026-09-25 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agt", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agtconfiguration",
            name="software_certificate_number",
            field=models.CharField(
                blank=True,
                help_text="Certificado AGT do programa que emite as faturas (ex.: HOST). Fornecido pelo cliente ou pelo fornecedor desse programa. O Gateway não emite faturas.",
                max_length=50,
                verbose_name="n.º de certificado do software de faturação",
            ),
        ),
        migrations.AlterField(
            model_name="agtconfiguration",
            name="software_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="nome do software de faturação"
            ),
        ),
        migrations.AlterField(
            model_name="agtconfiguration",
            name="software_version",
            field=models.CharField(
                blank=True,
                max_length=30,
                verbose_name="versão do software de faturação",
            ),
        ),
    ]
