# Generated by Django 5.2.17 on 2026-09-25 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agt", "0002_software_of_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="agtconfiguration",
            name="api_password_encrypted",
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name="agtconfiguration",
            name="api_username",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="utilizador da API"
            ),
        ),
        migrations.AddField(
            model_name="agtconfiguration",
            name="issuer_key_encrypted",
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name="agtconfiguration",
            name="issuer_key_info",
            field=models.CharField(blank=True, editable=False, max_length=120),
        ),
        migrations.AddField(
            model_name="agtconfiguration",
            name="producer_key_encrypted",
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name="agtconfiguration",
            name="producer_key_info",
            field=models.CharField(blank=True, editable=False, max_length=120),
        ),
        migrations.AddField(
            model_name="agtconfiguration",
            name="signature_version",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                verbose_name="versão da assinatura do software (signatureVersion)",
            ),
        ),
        migrations.AddField(
            model_name="agtconfiguration",
            name="software_signature",
            field=models.TextField(
                blank=True,
                help_text="Fornecida pelo produtor do software de faturação. Em alternativa, carregue a chave do produtor.",
                verbose_name="assinatura do software (jwsSoftwareSignature)",
            ),
        ),
        migrations.AlterField(
            model_name="agtconfiguration",
            name="base_url",
            field=models.URLField(
                blank=True,
                help_text="Vazio = o endereço oficial do ambiente escolhido (homologação ou produção).",
                verbose_name="endereço dos serviços AGT",
            ),
        ),
        migrations.AlterField(
            model_name="agtconfiguration",
            name="software_certificate_number",
            field=models.CharField(
                blank=True,
                help_text="Certificado AGT do programa que emite as faturas (ex.: HOST). Fornecido pelo cliente ou pelo fornecedor desse programa. O Gateway não emite faturas.",
                max_length=50,
                verbose_name="n.º de certificação do software (softwareValidationNumber)",
            ),
        ),
        migrations.AlterField(
            model_name="agtconfiguration",
            name="software_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="nome do software (productId)"
            ),
        ),
        migrations.AlterField(
            model_name="agtconfiguration",
            name="software_version",
            field=models.CharField(
                blank=True,
                max_length=30,
                verbose_name="versão do software (productVersion)",
            ),
        ),
    ]
