# Generated by Django 5.2.17 on 2026-09-25 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
        ("invoices", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "actor",
                    models.CharField(blank=True, max_length=150, verbose_name="autor"),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("action", models.CharField(max_length=60, verbose_name="ação")),
                ("object_type", models.CharField(blank=True, max_length=60)),
                ("object_id", models.CharField(blank=True, max_length=60)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_events",
                        to="companies.company",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "evento de auditoria",
                "verbose_name_plural": "eventos de auditoria",
                "ordering": ["-timestamp", "-id"],
            },
        ),
        migrations.CreateModel(
            name="IntegrationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("action", models.CharField(max_length=40, verbose_name="ação")),
                ("request_id", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(blank=True, max_length=30, verbose_name="estado"),
                ),
                (
                    "response_code",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="código de resposta"
                    ),
                ),
                (
                    "response_body",
                    models.TextField(blank=True, verbose_name="resposta"),
                ),
                ("error_message", models.TextField(blank=True, verbose_name="erro")),
                (
                    "simulated",
                    models.BooleanField(default=False, verbose_name="simulação"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integration_logs",
                        to="companies.company",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="integration_logs",
                        to="invoices.invoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "log de integração",
                "verbose_name_plural": "logs de integração",
                "ordering": ["-timestamp", "-id"],
            },
        ),
    ]
