# Generated by Django 5.2.17 on 2026-09-25 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="nome")),
                (
                    "nif",
                    models.CharField(max_length=20, unique=True, verbose_name="NIF"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="ativa")),
                (
                    "host_connection",
                    models.CharField(
                        blank=True,
                        help_text="'default' usa as variáveis HOST_DB_*; outro nome X usa HOST_X_DB_*. Vazio = sem HOST.",
                        max_length=50,
                        verbose_name="ligação HOST",
                    ),
                ),
                (
                    "agt_configuration",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="configuração AGT"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "empresa",
                "verbose_name_plural": "empresas",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ApiKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="nome")),
                (
                    "prefix",
                    models.CharField(editable=False, max_length=16, unique=True),
                ),
                ("key_hash", models.CharField(editable=False, max_length=64)),
                ("active", models.BooleanField(default=True, verbose_name="ativa")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "last_used_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "chave de API",
                "verbose_name_plural": "chaves de API",
            },
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Administrador"),
                            ("OPERATOR", "Operador"),
                            ("VIEWER", "Consulta"),
                        ],
                        default="VIEWER",
                        max_length=10,
                        verbose_name="papel",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="companies.company",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "acesso de utilizador",
                "verbose_name_plural": "acessos de utilizadores",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "company"), name="uniq_membership"
                    )
                ],
            },
        ),
    ]
