# Generated by Django 5.2.17 on 2026-09-25 14:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="host_connection",
            field=models.CharField(
                blank=True,
                help_text="'default' usa as variáveis HOST_DB_*; outro nome X usa HOST_X_DB_*. Vazio = sem HOST.",
                max_length=50,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[A-Za-z][A-Za-z0-9_]{0,49}$",
                        "Use só letras, números e _, a começar por letra (ex.: default, HOTEL2).",
                    )
                ],
                verbose_name="ligação HOST",
            ),
        ),
    ]
