# Generated by Django 5.2.17 on 2026-09-25 14:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0002_host_connection_validator"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Identifica a origem nos documentos (sistema de origem). Não alterar depois de importar.",
                        max_length=30,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z0-9][A-Z0-9_\\-]{0,29}$",
                                "Maiúsculas, números, _ ou -, até 30 (ex.: HOST, ERP-LOJA1).",
                            )
                        ],
                        verbose_name="código",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="nome")),
                (
                    "system",
                    models.CharField(
                        blank=True,
                        help_text="Sistema de faturação de origem (ex.: HOST Hotel Systems).",
                        max_length=100,
                        verbose_name="sistema",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("DATABASE", "Base de dados (leitura)"),
                            ("API", "API (o sistema envia)"),
                        ],
                        max_length=10,
                        verbose_name="tipo",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="ativa")),
                (
                    "connection",
                    models.CharField(
                        blank=True,
                        help_text="'default' usa HOST_DB_*; outro nome X usa HOST_X_DB_* no .env.",
                        max_length=50,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Za-z][A-Za-z0-9_]{0,49}$",
                                "Use só letras, números e _, a começar por letra (ex.: default, HOTEL2).",
                            )
                        ],
                        verbose_name="ligação",
                    ),
                ),
                (
                    "mapping",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="mapeamento"
                    ),
                ),
                (
                    "sync_cursor",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=200,
                        verbose_name="cursor",
                    ),
                ),
                (
                    "sync_locked_until",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "last_sync_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="última sincronização",
                    ),
                ),
                (
                    "last_sync_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Nunca"),
                            ("OK", "OK"),
                            ("PARTIAL", "Parcial"),
                            ("ERROR", "Erro"),
                        ],
                        editable=False,
                        max_length=10,
                    ),
                ),
                ("last_sync_message", models.TextField(blank=True, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "origem de documentos",
                "verbose_name_plural": "origens de documentos",
                "ordering": ["company__name", "code"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("company", "code"), name="uniq_source_code"
                    )
                ],
            },
        ),
    ]
