# Generated by Django 5.2.17 on 2026-09-25 15:37

import django.core.validators
from django.db import migrations, models


def keep_env_connections(apps, schema_editor):
    """Origens já existentes com ligação no .env continuam a usá-la."""
    DataSource = apps.get_model("sources", "DataSource")
    DataSource.objects.filter(kind="DATABASE").exclude(connection="").update(connection_mode="ENV")


class Migration(migrations.Migration):

    dependencies = [
        ("sources", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasource",
            name="connection_mode",
            field=models.CharField(
                choices=[
                    ("PANEL", "Configurada no painel"),
                    ("ENV", "Variáveis do ficheiro .env"),
                ],
                default="PANEL",
                max_length=5,
                verbose_name="configuração da ligação",
            ),
        ),
        migrations.AddField(
            model_name="datasource",
            name="db_engine",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mssql", "SQL Server"),
                    ("postgresql", "PostgreSQL"),
                    ("mysql", "MySQL"),
                    ("mariadb", "MariaDB"),
                    ("oracle", "Oracle"),
                    ("sqlite", "SQLite (ficheiro)"),
                    ("url", "Outro SGBD (URL SQLAlchemy)"),
                ],
                max_length=12,
                verbose_name="sistema de base de dados",
            ),
        ),
        migrations.AddField(
            model_name="datasource",
            name="db_host",
            field=models.CharField(
                blank=True,
                help_text="Nome ou IP. SQL Server com instância: SERVIDOR\\INSTANCIA.",
                max_length=255,
                verbose_name="servidor",
            ),
        ),
        migrations.AddField(
            model_name="datasource",
            name="db_name",
            field=models.CharField(
                blank=True,
                help_text="Nome da base de dados (Oracle: serviço; SQLite: caminho do ficheiro).",
                max_length=255,
                verbose_name="base de dados",
            ),
        ),
        migrations.AddField(
            model_name="datasource",
            name="db_odbc_driver",
            field=models.CharField(
                blank=True,
                help_text="Só SQL Server. Vazio = ODBC Driver 18 for SQL Server.",
                max_length=100,
                verbose_name="driver ODBC",
            ),
        ),
        migrations.AddField(
            model_name="datasource",
            name="db_options",
            field=models.CharField(
                blank=True,
                help_text="Formato chave=valor;chave=valor.",
                max_length=500,
                verbose_name="opções adicionais",
            ),
        ),
        migrations.AddField(
            model_name="datasource",
            name="db_password_encrypted",
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name="datasource",
            name="db_port",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Vazio = porta por omissão do sistema.",
                null=True,
                verbose_name="porta",
            ),
        ),
        migrations.AddField(
            model_name="datasource",
            name="db_trust_server_certificate",
            field=models.BooleanField(
                default=False,
                help_text="Só SQL Server com certificado próprio (autoassinado).",
                verbose_name="confiar no certificado do servidor",
            ),
        ),
        migrations.AddField(
            model_name="datasource",
            name="db_url_encrypted",
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name="datasource",
            name="db_user",
            field=models.CharField(
                blank=True,
                help_text="Utilizador só com permissão de leitura. SQL Server: vazio = autenticação Windows.",
                max_length=128,
                verbose_name="utilizador",
            ),
        ),
        migrations.AlterField(
            model_name="datasource",
            name="connection",
            field=models.CharField(
                blank=True,
                help_text="'default' usa HOST_DB_*; outro nome X usa HOST_X_DB_* no .env.",
                max_length=50,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[A-Za-z][A-Za-z0-9_]{0,49}$",
                        "Use só letras, números e _, a começar por letra (ex.: default, HOTEL2).",
                    )
                ],
                verbose_name="nome da ligação no .env",
            ),
        ),
        migrations.RunPython(keep_env_connections, migrations.RunPython.noop),
    ]
