# Generated by Django 5.2.17 on 2026-09-25 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sources", "0002_connection_in_panel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datasource",
            name="db_odbc_driver",
            field=models.CharField(
                blank=True,
                help_text="Só SQL Server. Vazio = o melhor instalado neste computador (ODBC Driver 18, senão 17).",
                max_length=100,
                verbose_name="driver ODBC",
            ),
        ),
    ]
